link:
  rails_tutorial: "https://www.railstutorial.org/"
  rails_tutorial_help: "https://www.railstutorial.org/help"
  rails_tutorial_book: "https://www.railstutorial.org/book"
  rails_tutorial_contact: "https://www.railstutorial.org/contact"
  learn_enough: "https://www.learnenough.com/"
  screen_casts: "https://screencasts.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
  size_avatar: 80
  gravatar_email: "https://gravatar.com/emails"
  index_avatar_size: 50

kaminari:
  page: 10

email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'

user:
  name_length: 50
  email_length: 255
  password_length: 6

check_box: 1
