link:
  rails_tutorial: "https://www.railstutorial.org/"
  rails_tutorial_help: "https://www.railstutorial.org/help"
  rails_tutorial_book: "https://www.railstutorial.org/book"
  rails_tutorial_contact: "https://www.railstutorial.org/contact"
  learn_enough: "https://www.learnenough.com/"
  screen_casts: "https://screencasts.railstutorial.org/"
  ruby_on_rails: "https://rubyonrails.org/"
